### ISSUE TITLE
Forcing users of "0.2" to upgrade?

### ISSUE THREAD

**Issue by dhardy** [dtolnay/semver-trick#7]
We've been using this trick with `rand_core`: both versions 0.2.2 and 0.3.1 are "upgrade shims". This works the majority of the time, but has resulted in several bug reports where users have ended up using two incompatible versions at the same time (e.g. 0.2.1 and 0.3.0), and are wondering why. *Usually* `cargo update` solves the problem for them (or some other mechanism to force update).

So is there some trick to force users of 0.2.1 and 0.3.0 to update to 0.2.2 / 0.3.1 which are upgrade shims? Perhaps using some other crate which depends on the upgrade shim would solve this, though it's not ideal.

**Comment by dtolnay** [comment]
I don't know of a way to do this. :(
