### ISSUE TITLE
Another instance of using semver trick: avoiding linking errors

### ISSUE THREAD

**Issue by Kixunil** [dtolnay/semver-trick#8]
First of all, thanks for the awesome idea! [I used it](https://github.com/rust-bitcoin/rust-secp256k1/issues/209) to avoid linking issues where one crate moved FFI to a separate crate and also bumped version. So when the depending crates were using different versions it duplicated the symbols.

I was thinking it might be worth mentioning it as another interesting use of the semver trick. What do you think?

**Comment by dtolnay** [comment]
I am not going to include this in the writeup in this repo, but thanks for sharing!
