### ISSUE TITLE
Trick to modify widely implemented traits

### ISSUE THREAD

**Issue by madsmtm** [dtolnay/semver-trick#9]
`raw-window-handle` is used as a bridge between window "provider" and window "consumer" crates. As of writing it has 82 reverse dependencies.

The main trait `HasRawWindowHandle` has changed from version `0.3` to `0.4`, specifically the return type of a method is a bit different.

But adding a blanket `impl<T: New> Old for T` means that all "provider" crates will be able to upgrade to `0.4` without breaking changes (because by implementing the new trait, they still implement the old one), see https://github.com/rust-windowing/raw-window-handle/pull/74.

Once most "provider" crates have upgraded, "consumer" crates can make a breaking change and require the new trait, but the breakage will be minimal because most "provider" crates already implement the new trait.

I'm posting this here in case anyone has some input on my reasoning, and maybe someone else can use this instance of the semver trick in the future.

**Comment by dtolnay** [comment]
Thanks for sharing!
